import type { Metadata } from "next";

import "./globals.css";
import MainHeader from "@/components/main-header/main-header";

export const metadata: Metadata = {
  title: "Ninja Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="text-gray-600 font-body">
        <div className="grid md:grid-cols-3">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
